name: Terraform Apply on Commit

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
        env:
          ACTIONS_STEP_DEBUG: true

      - uses: hashicorp/setup-terraform@v2

      - name: Run Terraform Scripts
        run: |
          chmod +x scripts/*.sh  # Set executable permissions
          ./scripts/terraform_network.sh
          ./scripts/terraform_webserver.sh